export const EPS = 1e-6
export const FACTOR = 80
export const SCREEN_WIDTH = 200
export const FAR_CLIPPING_PLANE = 10.0
export const NEAR_CLIPPING_PLANE = 0.1
export const PLAYER_SPEED = 2.0
export const PLAYER_TURN_SPEED = Math.PI * 0.75
export const PLAYER_FOV = Math.PI * 0.5
export const PLAYER_SIZE = 0.5
